name: Go Tests

on:
  push:
    branches:
      - '**' # Escuta todas as branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configurar o Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Substitua pela versão do Go que você usa

      # Step 3: Instalar dependências
      - name: Install dependencies
        working-directory: 17jan/ex03/testing-exercise
        run: go mod tidy

      # Step 4: Rodar os testes
      - name: Run tests
        working-directory: 17jan/ex03/testing-exercise
        run: go test ./... -v
